# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrole',
            name='role',
            field=models.CharField(choices=[('0', 'Manager'), ('1', 'Chef'), ('2', 'Cook'), ('3', 'Dishwasher')], max_length=2),
        ),
    ]
