# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160609_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('capable_roles', models.ManyToManyField(to='scheduler.WorkRole')),
            ],
        ),
    ]
