# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Day')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.WorkRole')),
            ],
        ),
    ]
