# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_shiftrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Employee')),
            ],
        ),
    ]
